# Generated by Django 4.2.4 on 2023-08-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estudiante_delete_curso_infoacademica_socioeconomica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='ID_TIPO_DOCUMENTO',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='infoacademica',
            name='ID_ASIGNATURA_ENCUESTA',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infoacademica',
            name='ID_NOTA_ACTUAL',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='infoacademica',
            name='ID_PROMEDIO_ACUMULADO',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='infoacademica',
            name='ID_PROMEDIO_SEMESTRE_ANT',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='socioeconomica',
            name='ID_INGRESO_FAMILIAR',
            field=models.IntegerField(),
        ),
    ]
