# Generated by Django 4.2.4 on 2023-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_estudiante_id_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='ID_SISBEN',
            field=models.CharField(max_length=10),
        ),
    ]
