# Generated by Django 4.2.5 on 2023-09-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_estudiante_id_sisben'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresados',
            fields=[
                ('ID_DOCUMENTO', models.IntegerField(primary_key=True, serialize=False)),
                ('ID_TIPO_DOCUMENTO', models.CharField(max_length=35)),
                ('ID_NOMBRE', models.CharField(max_length=50)),
                ('ID_NUM_CONTACTO', models.CharField(max_length=20)),
                ('ID_GENERO', models.IntegerField(null=True)),
                ('ID_EDAD', models.IntegerField()),
                ('ID_ESTADO_CIVIL', models.IntegerField()),
                ('ID_ETNIA', models.IntegerField()),
                ('ID_EMAIL', models.CharField(max_length=40)),
                ('ID_ESTRATO', models.IntegerField()),
                ('ID_prueba', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EgreAcademica',
            fields=[
                ('ID_EGRESADO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.egresados')),
                ('ID_TITULO', models.IntegerField()),
                ('ID_SEMESTRE_INICIO', models.IntegerField()),
                ('ID_SEMESTRES_CURSADOS', models.IntegerField()),
                ('ID_PROMEDIO_ACUMULADO', models.FloatField()),
                ('ID_SEMESTRE_FIN', models.IntegerField()),
                ('ID_FECHA_GRADO', models.IntegerField()),
                ('ID_PRACTICAS', models.IntegerField()),
                ('ID_POSTGRADO', models.IntegerField()),
                ('ID_POSTGRADO_NIVEL', models.IntegerField()),
                ('ID_POSTGRADO_LUGAR', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EgreLaboral',
            fields=[
                ('ID_EGRESADO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.egresados')),
                ('ID_TRABAJA', models.IntegerField()),
                ('ID_TRABAJA_PAIS', models.CharField(max_length=35)),
                ('ID_TRABAJA_CIUDAD', models.CharField(max_length=30)),
                ('ID_TRABAJA_SITUACION', models.IntegerField()),
                ('ID_TRABAJA_PERFIL', models.IntegerField()),
                ('ID_TRABAJA_SECTOR', models.IntegerField()),
                ('ID_TRABAJA_TIEMPO', models.IntegerField()),
                ('ID_TRABAJA_NIVEL', models.IntegerField()),
                ('ID_TRABAJA_TIEMPO_PRIMER', models.IntegerField()),
                ('ID_TRABAJA_MEDIO', models.IntegerField()),
                ('ID_TRABAJA_SECTOR_DOS', models.IntegerField()),
                ('ID_TRABAJA_SECTOR_TRES', models.IntegerField()),
                ('ID_TRABAJA_REQUISITOS', models.IntegerField()),
                ('ID_TRABAJA_RANGO', models.IntegerField()),
                ('ID_TRABAJA_RECONOCIMIENTO', models.IntegerField()),
                ('ID_EMPRESA', models.IntegerField()),
                ('ID_EMPRESA_ANTES', models.IntegerField()),
                ('ID_EMPRESA_SECTOR', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='EgreMotivacion',
            fields=[
                ('ID_EGRESADO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.egresados')),
                ('ID_MOT_PREGRADO', models.IntegerField()),
                ('ID_MOT_VOLUMEN', models.IntegerField()),
                ('ID_MOT_NIVELS', models.IntegerField()),
                ('ID_MOT_AMBIENTE', models.IntegerField()),
                ('ID_MOT_FORTALECER', models.IntegerField()),
                ('ID_MOT_MATERIAS', models.CharField(max_length=60)),
                ('ID_MOT_APOYO', models.IntegerField()),
                ('ID_MOT_RECURSOS', models.IntegerField()),
                ('ID_MOT_MODALIDAD', models.IntegerField()),
                ('ID_MOT_MODALIDAD_P', models.IntegerField()),
                ('ID_MOT_MODALIDAD_T', models.IntegerField()),
                ('ID_MOT_PROFUNDIZACION', models.IntegerField()),
                ('ID_MOT_INGRESAR', models.IntegerField()),
                ('ID_MOT_CONOCIMIENTOS', models.IntegerField()),
                ('ID_MOT_CONTRIBUCION', models.IntegerField()),
                ('ID_MOT_CALIDAD', models.IntegerField()),
                ('ID_MOT_FAVORECIDO', models.IntegerField()),
                ('ID_MOT_POST_CONT', models.IntegerField()),
            ],
        ),
    ]
