# Generated by Django 4.2.5 on 2023-09-23 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_egresados_id_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreacademica',
            name='ID_EGRESADO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info_academica', serialize=False, to='api.egresados'),
        ),
        migrations.AlterField(
            model_name='egrelaboral',
            name='ID_EGRESADO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info_laboral', serialize=False, to='api.egresados'),
        ),
        migrations.AlterField(
            model_name='egremotivacion',
            name='ID_EGRESADO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info_motivacion', serialize=False, to='api.egresados'),
        ),
    ]
