# Generated by Django 4.2.5 on 2023-10-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_egreacademica_id_nivel_egreacademica_id_segndalengua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresados',
            name='ID_EMAIL',
            field=models.CharField(max_length=50),
        ),
    ]
