# Generated by Django 4.2.5 on 2023-10-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_egresados_id_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreacademica',
            name='ID_SEMESTRE_INICIO',
            field=models.CharField(max_length=15),
        ),
    ]
