# Generated by Django 4.2.4 on 2023-08-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_estudiante_id_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='ID_NUM_CONTACTO',
            field=models.CharField(max_length=20),
        ),
    ]
