# Generated by Django 4.2.4 on 2023-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_estudiante_id_num_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoacademica',
            name='ID_SEMESTRE_INICIO',
            field=models.IntegerField(),
        ),
    ]
